Controllers films users
Peppilotta/java-filmorate pull request #4
Opened 2023-02-14 13:46 UTC by Peppilotta

2023-02-16 09:28 UTC, kalitva requested changes

2023-02-16 09:28 UTC, kalitva commented on pom.xml
> +	<parent>
В проекте должны использоваться либо везде табы, либо везде пробелы, иначе будет путаница с 
отступами. Замени все табы на пробелы

В intellij нажми Edit --> Convert Indents --> To spaces

2023-02-16 09:28 UTC, kalitva commented on pom.xml
> +		<relativePath/> <!-- lookup parent from repository -->
Удали коммент

2023-02-16 09:28 UTC, kalitva commented on pom.xml
> +			<version>1.18.20</version>
Спринг бут управляет версиями популярных зависимостей, лучше не переопределяй

2023-02-16 09:28 UTC, kalitva commented on pom.xml
> +			<artifactId>jakarta.validation-api</artifactId>
Эта зависимость уже объявлена выше. Удали, а в импортах аннотаций замени `javax --> jakarta`

2023-02-16 09:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
Убери проверки, которые уже проверяются аннотациями над полями в моделях, здесь должна остаться только провера на дату релиза

2023-02-16 09:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    }
То же самое, здесь оставь только логику, где сетится имя

2023-02-16 09:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(min = 1, max = 200, message = "Description size mast be between 1 and 200")
`@Size` рассматривает null ка валидное значение, добавь `@NotNull`

2023-02-16 09:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Min(1)
Лучше `@Positive`

2023-02-16 09:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Email(message = "Wrong email")
Добавь `@NotNull`

2023-02-16 09:28 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private LocalDate birthday;
`@Past`

2023-02-16 09:28 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        film.setDescription("Too long description. Too long description. " +
`"Too long description".repeat(10)`

2023-02-16 09:28 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +@SpringBootTest
Удали аннотацию, спринг будет поднимать контекст без надобности

2023-02-16 09:28 UTC, kalitva commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +package ru.yandex.practicum.filmorate;
Давай удалим этот файл

2023-02-19 12:43 UTC, kalitva requested changes

2023-02-19 12:43 UTC, kalitva commented on pom.xml
> +        <dependency>
Это удали, должна использоваться зависимость spring-boot-starter-validation

2023-02-19 12:43 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import jakarta.validation.Valid;
После того, как удалишь лишние зависимости это не будет компилироваться. Нужно будет все `jakarta` заменить на `javax`

2023-02-19 12:43 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ProgenitorController.java
> +public abstract class ProgenitorController<P extends Progenitor> {
Я же сказал удалить иерархию наследования

2023-02-19 12:43 UTC, kalitva commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
Это удали

2023-02-19 12:43 UTC, kalitva commented on pom.xml
> +            <groupId>junit</groupId>
Это тоже

2023-02-19 12:43 UTC, kalitva commented on pom.xml
> +            <groupId>org.hibernate.validator</groupId>
Это тоже

2023-02-19 12:43 UTC, kalitva commented on pom.xml
> +            <groupId>org.glassfish.expressly</groupId>
Это удали

2023-02-20 07:53 UTC, kalitva requested changes

2023-02-20 07:53 UTC, kalitva commented on pom.xml
> +            <version>1.18.20</version>
Спринг бут управляет версиями большинства популярных зависимостей, лучше не переопределять

2023-02-20 07:53 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PostMapping("/films")
Вынеси общую часть маппинга в `@RequestMapping("/films")` на уровне класса

https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-requestmapping

2023-02-20 07:53 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (films.containsKey(id)) {
Инвертируй условие затем убери else

https://www.codementor.io/@clintwinter/use-guard-clauses-for-cleaner-code-1rrsczgwxp

2023-02-20 07:53 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.parse("28.12.1895",
Вынеси дату в константу

2023-02-20 07:53 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (Objects.isNull(name) || name.trim().length() == 0) {
Это не относится к валидации, или перемести в методы или создай отдельный метод для этого блока

2023-02-20 07:53 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull
Лучше поля с аннотациями отделить пустыми линиями, легче читается когда много полей

2023-02-20 07:53 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Progenitor.java
> +public abstract class Progenitor {
Не надо наследования здесь тоже

2023-02-20 07:53 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
Зачем эта проверка? Есть же аннотация `@Past`

2023-02-20 18:15 UTC, Peppilotta commented on pom.xml
> +            <version>1.18.20</version>
без этой зависимости не работает(

2023-02-21 07:30 UTC, kalitva approved these changes

2023-02-21 07:30 UTC, kalitva commented on pom.xml
> +            <version>1.18.20</version>
Речь идет о том чтобы не указывать версию

2023-02-21 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PostMapping("/users")
Здесь тоже - общий префикс в `@RequestMapping`

2023-02-21 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (users.containsKey(id)) {
guard clause - инвертируй условие, убери else

2023-02-21 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    long id;
private

2023-02-21 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    long id;
private

2023-02-21 07:30 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull
Примитив не может быть null

2023-02-21 17:59 UTC, merged