feat: ссзданы друзья и лайки
Peppilotta/java-filmorate pull request #5
Opened 2023-02-25 09:23 UTC by Peppilotta

2023-02-26 18:48 UTC, kalitva requested changes

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionController.java
> +        return Map.of("error", "film id exception",
Здесь нужно обязательно залогировать перехваченные исключения

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionController.java
> +                "errorMessage", e.getMessage());
Лучше `errorMessage --> message`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final InMemoryFilmStorage filmStorage;
Все взаимодействия - через сервисы, стораджей в контроллере не должно быть

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/ValidationOfInputNumbers.java
> +public class ValidationOfInputNumbers {
Непонятно что ты здесь валидируешь, и непонятно зачем. Удали этот класс

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final ValidationOfInputNumbers validationOfInputNumbers;
Это удали

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info("POST request for film {}", film);
Давай перенесем логирование в сервисы

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilm(@PathVariable String id) {
`@PathVariable long id`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.getFilm(filmId);
В этом методе должна быть только одна строка `return filmService.getFilm(id)`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmLikeController.java
> +public class FilmLikeController {
1. Все эти методы должны быть в `FilmController`
2. Методы контроллеров практически не должны содержать какую-либо логику, только определения маппингов и делегирование http запросов к сервисам

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
Те же замечания, что и для `FilmController`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserFriendsController.java
> +public class UserFriendsController {
Тоже, перенеси эти методы в `UserController`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotExist.java
> +public class FilmNotExist extends RuntimeException {
Классы исключений заканчиваются на `Exception` - `FilmDoesNotExistException`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/exception/UserNotExist.java
> +public class UserNotExist extends RuntimeException {
`UserDoesNotExistException`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +        int checkedCount = allFilms.size();
Зачем это? Пожалуйста, не делай ненужных проверок

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +        return allFilms
Пожалуйста, сортируй в стриме

```
        return allFilms
                .stream()
                .sorted(Comparator.comparing(f -> f.getLikes().size(), Comparator.reverseOrder()))
                .limit(count)
                .collect(Collectors.toList());
```

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends;
`friendIds`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +    public void testIfExistFilmWithId(long id) {
Не думаю, что для этого нужен отдельный метод

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    void testIfExistFilmWithId(long id);
Не надо void методов в классах хранилища, сделай чтобы возвращал boolean и назови `containsFilm`. То же самое для `UserStorage`

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    public void validateDateCreation(Film film) {
Это должно быть в сервисе

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    public void fillUserName(User user) {
Это должно быть в сервисе

2023-02-26 18:48 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes;
` private Set<Long> likeIds = new HashSet<>()`

2023-02-27 11:14 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/sevice/ValidationOfInputNumbers.java
> +public class ValidationOfInputNumbers {
выделила в класс проверку на валидность id, который должен быть числовым и > 0
иначе нужно в каждом контроллере такую проверку создавать

2023-02-28 13:59 UTC, kalitva requested changes

2023-02-28 13:59 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionController.java
> +        log.error("Film with this id not exist.");
Добавь вторым параметром само исключение чтобы залогировался стэк трэйс

https://stackoverflow.com/questions/3988788/what-is-a-stack-trace-and-how-can-i-use-it-to-debug-my-application-errors

2023-02-28 13:59 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info("POST request for film {}", film);
Почему не перенесено в сервис?

2023-02-28 13:59 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getFilm(@PathVariable String id) {
Почему String? Написал же - `long`

2023-02-28 13:59 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void validatePositive(long id) {
Пожалуйста, убери эту проверку

2023-02-28 13:59 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private long validateIdIsNumber(String id) throws IdIsNotNumber {
Это не нужно, спринг сам сконвертирует реквест параметр в тип, указанный в параметре

2023-03-02 18:29 UTC, kalitva approved these changes

2023-03-02 18:29 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +    private final LocalDate filmsStart = LocalDate.parse("28.12.1895",
Напоминаю как оформляются константы:

Константа это `static final` поле класса c описательным названием, написанным в upper snake case, например

`private static final int MOMMA_TOLD_ME_TIMES = 1000`

Почему в таком виде не очень хорошо:
https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования

Как оформляются константы
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2023-03-02 18:29 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/UserService.java
> +    public List<User> getFriendIds(long userId) {
`getFriendIds --> getFriends`

2023-03-02 18:29 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/UserService.java
> +        if (Objects.isNull(name) || name.trim().length() == 0) {
`name.trim().length() == 0 --> name.isBlank()`

2023-03-02 18:29 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/UserService.java
> +    public List<User> getCommonFriends(long user1Id, long user2Id) {
Лучше `userId` и `otherUserId`

2023-03-02 18:29 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/UserService.java
> +        Set<Long> user2Friends = userStorage.getUser(user2Id).getFriendIds();
Лучше `userFriendIds` и `otherUserFriendIds`

2023-03-02 18:29 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/UserService.java
> +        if (cross.isEmpty()) {
Я бы попроще сделал:

```
        return user1Friends
                .stream()
                .filter(user2Friends::contains)
                .map(userStorage::getUser)
                .collect(Collectors.toList());
```

На твое усмотрение

2023-03-02 18:29 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    }
Имелось ввиду `return films.contains(id)`, а исключение выбрасывать уже по результату вызова этого метода

2023-03-05 11:25 UTC, merged