Add database
Peppilotta/java-filmorate pull request #6
Opened 2023-03-18 00:16 UTC by Peppilotta

2023-03-19 17:51 UTC, kalitva requested changes

2023-03-19 17:51 UTC, kalitva commented on db/filmorate.mv.db
Нужно удалить папку `db`, затем добавить в гитигнор `db/`, этих файлов не должно быть в репозитории

2023-03-19 17:51 UTC, kalitva commented on pom.xml
> +<!--
Удали закомментированный код

2023-03-19 17:51 UTC, kalitva commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
Удали эту зависимость, мы jpa еще не проходили. Добавь `spring-boot-starter-jdbc`

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/ExceptionController.java
>      }
Cделай один обработчик для все обработчиков, возвращающих 404, для этого нужно в `@ExceptionHandler` передать массив классов исключений

https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#mvc-ann-exceptionhandler

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -@RequestMapping("/films")
Это должно было остаться, для маппингов `/mpa*` и `/genres*` - отдельные контроллеры

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/exception/MpaDoesNotExistException.java
> +}
Вообще нет необходимости создавать исключение для каждой сущности, вполне хватит одного `NotFoundException`

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int rate;
Это поле не нужно, удали

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenre.java
> +public class FilmGenre {
Для связывающей таблицы сущность не нужна, пожалуйста, удали

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmMpa.java
> +public class FilmMpa {
`FilmMpa --> Mpa`

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +public class Friend {
Эта сущность не нужна

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
>  public class Friendship {
Не нужна сущность

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    @PositiveOrZero
Айди должно генериться в БД, а не приходить извне, соответственно эта валидация не нужна

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +public class Like {
Сущность для лайка не нужна

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +    public FilmService(@Qualifier("filmDbStorage") FilmStorage filmStorage,
Можно удалить инмемори реализации стораджей, тебе будет удобнее без них

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +    public Set<Genre> getGenres() {
Для жанров - отдельные сервис и сторадж

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +    public Set<Mpa> getMpas() {
Для mpa также - отдельные сервис и сторадж

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
>      public List<Film> getCountFavoriteFilms(int count) {
`getCountFavoriteFilms --> getFavoriteFilms`, хотя вообще правильнее - `getTheMostPopularFilms`

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private static final String GET_BEST_FILMS =
Отдели константы запросов пустыми линиями чтобы легче читалось

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private static final String DELETE_FILM_MPA = "DELETE FROM film_mpas where film_id=? and mpa_id=? ";
Пожалуйста, выбери код стайл для sql и придерживайся его **во всем приложении**, иначе это выглядит небрежно. Наиболее распространенный - ключевые слова и типы  в upper case, названия полей и таблиц - в lower case, можно наоборот, главное чтобы везде было единообразно

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Optional<Set<Genre>> getFilmGenres(long filmId) {
Не надо коллекции заворачиавть в `Optional`, если из стораджа придет пустая коллекция - это абсолютно окей

2023-03-19 17:51 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        if (film.isEmpty()) {
Все эти валидации должны быть в сервисах, для этого у тебя есть методы типа `containsFilm`. Это важно, проверь везде

2023-03-19 20:55 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/exception/MpaDoesNotExistException.java
> +}
а я уже так классно со всякими разными сообщениями сделала)))

2023-03-19 20:58 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int rate;
а его и нет
ты видишь какой-то старый вариант

2023-03-19 21:00 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmGenre.java
> +public class FilmGenre {
я этот класс создала, чтоб легче было добавить запись в таблицу. Точно нужно удалить?

2023-03-19 21:03 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmMpa.java
> +public class FilmMpa {
эта сущность тоже для того, чтоб легко записать строку в таблицу.
метод toMap()
иначе придётся просто вносить через SQL INSERT

2023-03-19 21:03 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/model/Friend.java
> +public class Friend {
это тоже ради toMap()

2023-03-19 21:05 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/model/Friendship.java
>  public class Friendship {
это тоже ради toMap()
точно удалять?

2023-03-19 21:05 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/model/Like.java
> +public class Like {
ради toMap()

2023-03-19 21:06 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +    public FilmService(@Qualifier("filmDbStorage") FilmStorage filmStorage,
Ура! они очень мешали

2023-03-19 21:08 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
> +    public Set<Genre> getGenres() {
Прекрасно! Это тоже было очень неудобно

2023-03-20 19:34 UTC, kalitva requested changes

2023-03-20 19:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/sevice/FilmService.java
>          userStorage.containsUser(userId);
Это должно работать таким образом:

```
if (!userStorage.contains(userId)) {
    throw UserNotFound...
}
```

Также здесь необходимо проверить наличие фильма. Это важноe замечание, проверь, что:
1. Все такие проверки происходят в сервисах, а не в стораджах
2. Исключение выбрасывается из сервиса, а не из метода `contains`

2023-03-20 19:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +    boolean deleteLike(long filmId, long userId);
void

2023-03-20 19:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        film.setMpa(mpaStorage.getMpa(mpa.getId()));
Нужно лишь только засетать фильму mpa_id, это должно быть в том же запросе, где обновляется фильм

2023-03-20 19:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                .usingGeneratedKeyColumns("id");
То же самое про жанр

2023-03-20 19:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private long mapRowToFilmId(ResultSet rs, long rowNum) throws SQLException {
Не понадобится, не забудь удалить

2023-03-20 19:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Set<Genre> getFilmGenres(long filmId) {
private

2023-03-20 19:34 UTC, kalitva commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public Mpa getFilmMpa(long filmId) {
Mpa должен джойниться к фильму, фильм достается *одним* запросом, это строго обязательное требование

2023-03-21 18:54 UTC, Peppilotta commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            updateFilmGenres(removeDoubles(genres), film.getId());
не поняла почему
но добавила

2023-03-21 20:36 UTC, kalitva approved these changes

2023-03-30 17:55 UTC, merged